# Generated by Django 5.0.6 on 2024-06-20 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crud", "0002_student_classroom"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("profile_pic", models.FileField(blank=True, null=True, upload_to="")),
                ("phone", models.CharField(max_length=10)),
                ("roll", models.PositiveIntegerField()),
                ("bio", models.TextField(max_length=1000)),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="crud.student"
                    ),
                ),
            ],
        ),
    ]
